### ISSUE TITLE
How to set text alignment in Textarea?

### ISSUE THREAD

**Issue by huangxin168** [TorbenFricke/formify#2]
I found this project and  it's cool!

when I try this code, can not find how to set text alignment to be "center" in Textarea:

from formify import *

ui = ControlTextarea("Write Here", variable_name="text")

MainWindow(ui, title="First App", margin=8)

help me please.

**Comment by TorbenFricke** [comment]
Hi! You can access the underlying QTextEdit ising `.control`:

```python
from formify import *
from PySide6.QtCore import Qt

ui = ControlTextarea("Write Here", variable_name="text")
ui.control.setAlignment(Qt.AlignHCenter)

MainWindow(ui, title="First App", margin=8)
```
